android.builtInKotlin=true
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=false
android.enableAppCompileTimeRClass=false
android.enableJetifier=true
android.newDsl=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.r8.optimizedResourceShrinking=true
android.r8.strictFullModeForKeepRules=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.uniquePackageNames=true
android.useAndroidX=true
android.usesSdkInManifest.disallowed=true